/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javagameapplication;

import java.awt.Color;

/**
 * Quiz game window
 * @author Kamil Matecki
 */
public class GameWindow extends javax.swing.JFrame {

    //instance of GameController.java
    private GameController gameController;
    
    //other screens
    private OpenWindow openWindow;
    private PlayerPanel playerPanel;
    
    /**
     * Constructor of GameWindow.java (init windows and set them)
     */
    public GameWindow() {
        initComponents();
        this.gameController = new GameController();
        prepareGame(gameController);
        setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButton5.setText("->");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel2.setText("Suma punktów");

        jLabel3.setText("na");

        jLabel4.setText("0");

        jLabel5.setText("0");

        jButton6.setText("Powrót do menu głównego");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addGap(41, 41, 41))
                            .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(85, 85, 85))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addGap(103, 103, 103))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    
    /**
     * Method that prepare all windows by preparing question and answer for quiz,
     * filling, set color and setting them visable
     * @param gameController 
     */
    private void prepareGame(GameController gameController){
        gameController.prepareQuiz();
        jButton1.setBackground(Color.LIGHT_GRAY);
        jButton2.setBackground(Color.LIGHT_GRAY);
        jButton3.setBackground(Color.LIGHT_GRAY);
        jButton4.setBackground(Color.LIGHT_GRAY);
        jButton7.setVisible(false);
        jButton8.setVisible(false);
        jButton9.setVisible(false);
        jLabel6.setVisible(false);
        jButton7.setBackground(Color.LIGHT_GRAY);
        jButton8.setBackground(Color.LIGHT_GRAY);
        jButton9.setBackground(Color.LIGHT_GRAY);
        jLabel1.setText("Do jakiego województwa należy tablica "+gameController.getAskForQuiz().getCardName()+"?");
        jButton1.setText("A. "+gameController.getAnswersList().get(0)+"GO");
        jButton2.setText("B. "+gameController.getAnswersList().get(1)+"GO");
        jButton3.setText("C. "+gameController.getAnswersList().get(2)+"GO");
        jButton4.setText("D. "+gameController.getAnswersList().get(3)+"GO");
        jLabel4.setText(Integer.toString(gameController.getCurrentScore()));
        jLabel5.setText(Integer.toString(gameController.getProgress()));
        gameController.setItWasAnswer(false);
        gameController.setItWasSecondAnswer(false);
        jButton5.setVisible(false);
        setVisible(true);
    }
    
    private void prepareSecondStage(){
        jLabel6.setVisible(true);
        jLabel6.setText("BONUS PUNKTOWY! Do jakiego miasta należy ta tablica rejestracyjna?");
        jButton7.setVisible(true);
        jButton7.setText(gameController.getAnswersForSecondStage().get(0).getCardCity());
        jButton8.setVisible(true);
        jButton8.setText(gameController.getAnswersForSecondStage().get(1).getCardCity());
        jButton9.setVisible(true);
        jButton9.setText(gameController.getAnswersForSecondStage().get(2).getCardCity());
    }
    
    /**
     * Method that pause action for duration time
     * @param duration 
     */
    private void waitFor(int duration){
        try {
            Thread.sleep(duration); 
        } catch (InterruptedException ex){
            Thread.currentThread().interrupt();
        }
    }
    
    /**
     * jButton3 on click method (third answer)
     * @param evt 
     */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(!gameController.getItWasAnswer()){
            gameController.getResponse().setCheckedProvince(gameController.getAnswersList().get(2));
            waitFor(1000);
            if(gameController.checkResponse()){
                jButton3.setBackground(Color.GREEN);
                gameController.getPlayer().addScore();
                gameController.setCurrentScore(gameController.getCurrentScore()+1);
                prepareSecondStage();
            } else {
                jButton3.setBackground(Color.RED);
                jButton5.setVisible(true);
            }
            gameController.setItWasAnswer(true);
            gameController.addProgress();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * jButton1 on click method (first answer)
     * @param evt 
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(!gameController.getItWasAnswer()){
            gameController.getResponse().setCheckedProvince(gameController.getAnswersList().get(0));
            waitFor(1000);
            if(gameController.checkResponse()){
                jButton1.setBackground(Color.GREEN);
                gameController.getPlayer().addScore();
                gameController.setCurrentScore(gameController.getCurrentScore()+1);
                prepareSecondStage();
            } else {
                jButton1.setBackground(Color.RED);
                jButton5.setVisible(true);
            }
            gameController.setItWasAnswer(true);
            gameController.addProgress();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * jButton2 on click method (second answer)
     * @param evt 
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(!gameController.getItWasAnswer()){
            gameController.getResponse().setCheckedProvince(gameController.getAnswersList().get(1));
            waitFor(1000);
            if(gameController.checkResponse()){
                jButton2.setBackground(Color.GREEN);
                gameController.getPlayer().addScore();
                gameController.setCurrentScore(gameController.getCurrentScore()+1);
                prepareSecondStage();
            } else {
                jButton2.setBackground(Color.RED);
                jButton5.setVisible(true);
            }
            gameController.setItWasAnswer(true);
            gameController.addProgress();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * jButton4 on click method (fourth answer)
     * @param evt 
     */
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(!gameController.getItWasAnswer()){
            gameController.getResponse().setCheckedProvince(gameController.getAnswersList().get(3));
            waitFor(1000);
            if(gameController.checkResponse()){
                jButton4.setBackground(Color.GREEN);
                gameController.getPlayer().addScore();
                gameController.setCurrentScore(gameController.getCurrentScore()+1);
                prepareSecondStage();
            } else {
                jButton4.setBackground(Color.RED);
                jButton5.setVisible(true);
            }
            gameController.setItWasAnswer(true);
            gameController.addProgress();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * jButton5 on click method (next question)
     * @param evt 
     */
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(gameController.getItWasAnswer()){
            gameController.setItWasAnswer(false);
            prepareGame(gameController);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        setVisible(false);
        openWindow.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if(!gameController.isItWasSecondAnswer()){
            gameController.getResponse().setCheckedProvince(gameController.getAnswersForSecondStage().get(0).getCardCity());
            waitFor(1000);
            
            if(gameController.checkResponseSecondStage()){
                jButton7.setBackground(Color.GREEN);
                for(int i=0; i<2; i++){
                    gameController.getPlayer().addScore();
                    gameController.setCurrentScore(gameController.getCurrentScore()+1);
                }
            } else {
                jButton7.setBackground(Color.RED);
            }
            jButton5.setVisible(true);
            gameController.setItWasSecondAnswer(true);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if(!gameController.isItWasSecondAnswer()){
            gameController.getResponse().setCheckedProvince(gameController.getAnswersForSecondStage().get(1).getCardCity());
            waitFor(1000);
            
            if(gameController.checkResponseSecondStage()){
                jButton8.setBackground(Color.GREEN);
                for(int i=0; i<2; i++){
                    gameController.getPlayer().addScore();
                    gameController.setCurrentScore(gameController.getCurrentScore()+1);
                }
            } else {
                jButton8.setBackground(Color.RED);
            }
            jButton5.setVisible(true);
            gameController.setItWasSecondAnswer(true);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if(!gameController.isItWasSecondAnswer()){
            gameController.getResponse().setCheckedProvince(gameController.getAnswersForSecondStage().get(2).getCardCity());
            waitFor(1000);
            
            if(gameController.checkResponseSecondStage()){
                jButton9.setBackground(Color.GREEN);
                for(int i=0; i<2; i++){
                    gameController.getPlayer().addScore();
                    gameController.setCurrentScore(gameController.getCurrentScore()+1);
                }
            } else {
                jButton9.setBackground(Color.RED);
            }
            jButton5.setVisible(true);
            gameController.setItWasSecondAnswer(true);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    
    /**
     * Main method
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
            
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables

    
    
    
    
    //getters and setters
    
    /**
     * @return the gameController
     */
    public GameController getGameController() {
        return gameController;
    }

    /**
     * @param gameController the gameController to set
     */
    public void setGameController(GameController gameController) {
        this.gameController = gameController;
    }

    /**
     * @return the openWindow
     */
    public OpenWindow getOpenWindow() {
        return openWindow;
    }

    /**
     * @param aOpenWindow the openWindow to set
     */
    public void setOpenWindow(OpenWindow aOpenWindow) {
        openWindow = aOpenWindow;
    }

    /**
     * @return the playerPanel
     */
    public PlayerPanel getPlayerPanel() {
        return playerPanel;
    }

    /**
     * @param playerPanel the playerPanel to set
     */
    public void setPlayerPanel(PlayerPanel playerPanel) {
        this.playerPanel = playerPanel;
    }
}
